# Generated by Django 4.1.7 on 2023-03-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("email", models.TextField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bookkeeping",
            },
        ),
    ]
