# Generated by Django 4.1.7 on 2023-04-22 16:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('UserID', models.BigAutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=320, unique=True)),
                ('UserNickname', models.CharField(max_length=320)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('LedgerID', models.BigAutoField(primary_key=True, serialize=False)),
                ('LedgerName', models.TextField(default='None', max_length=320)),
                ('LedgerType', models.TextField(default='None', max_length=320)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('OwnerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('RecordID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ItemName', models.TextField(default='None', max_length=320)),
                ('ItemType', models.TextField(default='None', max_length=320)),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BoughtDate', models.DateTimeField(default=datetime.datetime.now)),
                ('LedgerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ledger')),
                ('Payby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShouldPay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RecordID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.record')),
                ('ShareUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('ReceiptID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BuyDate', models.DateTimeField(default='None')),
                ('StatusCode', models.TextField(default='None', max_length=320)),
                ('RecordID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.record')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccessLevel', models.TextField(default='None', max_length=320)),
                ('LedgerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ledger')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
