# Generated by Django 4.1.7 on 2023-03-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ledger",
            fields=[
                ("LedgerID", models.BigAutoField(primary_key=True, serialize=False)),
                ("Type", models.TextField(default="None", max_length=320)),
                ("CreateDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                ("RecordID", models.BigAutoField(primary_key=True, serialize=False)),
                ("ItemName", models.TextField(default="None", max_length=320)),
                ("ItemType", models.TextField(default="None", max_length=320)),
                ("Cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Payby", models.TextField(default="None", max_length=320)),
                (
                    "LedgerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ledger"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("UserID", models.BigAutoField(primary_key=True, serialize=False)),
                ("Username", models.TextField(default="None", max_length=320)),
                ("Email", models.TextField(default="None", max_length=320)),
                ("CreateDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SharePay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ShouldPay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "RecordID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.record"
                    ),
                ),
                (
                    "ShareUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                ("ReceiptID", models.BigAutoField(primary_key=True, serialize=False)),
                ("BuyDate", models.DateTimeField(default="None")),
                ("StatusCode", models.TextField(default="None", max_length=320)),
                (
                    "RecordID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.record"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AccessLevel", models.TextField(default="None", max_length=320)),
                (
                    "LedgerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ledger"
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ledger",
            name="OwnerID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
    ]
